services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    _instanceof:
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [setContainer, ['@Psr\Container\ContainerInterface']]

    Newhorizondesign\ContaoChartjsDiagrammsBundle\Widget\Backend\MultiTextWidget:
        tags:
            - { name: contao.form.widget, alias: multiTextWidget }

    Newhorizondesign\ContaoChartjsDiagrammsBundle\EventListener\IncludeCssJsListener: ~
    Newhorizondesign\ContaoChartjsDiagrammsBundle\Controller\FrontendModule\ListenChartjsModulesController: ~
    Newhorizondesign\ContaoChartjsDiagrammsBundle\Controller\ContentElement\DiagramElementController: ~